config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

    root 'home#dashboard'
    mount Sidekiq::Web, at: '/sidekiq'

    get 'password_resets/new'

    get 'password_resets/edit'
    get 'password_resets' => 'password_resets#new'
    get 'login/create'

    get 'login/destroy'
    get '/new' => 'users#new', :as => 'sign_up'

    get '/login' => 'login#new'
    post '/login' => 'login#create'
    get '/logout' => 'login#destroy'
    get '/confirmation_page' => 'login#confirmation'
    get '/lists/:id/showList' => 'lists#showList', as: 'list_showList'
    get '/lists/:id/showList_blocker' => 'lists#showList_blocker', as: 'showList_blocker'
    get '/task/:id/showTask' => 'tasks#showTask', as: 'showTask'

    post 'users/resend_activation' => 'users#resend_activation'

    resources :notifications do
      collection do
        post :mark_as_read
      end
    end
    resources :sessions
    resources :users do
      resources :lists, :name_prefix => "user_"
      member do
        post :updateAvatar
        post :updateEmail
        post :updatePassword
        get :settings
        get :notifications
        get :crop
        get :setCoord
        get :showCompletedTask
      end
    end

    resources :lists do
      resources :tasks, :name_prefix => "list_" do
        put :sort, on: :collection
      end
      resources :invitations do
        member do
          get :resend_invitation
        end
      end
      resources :collaboration_users, :controller => 'users', :defaults => {:type => 'collaborator'} do
        put :sort, on: :collection
      end
      get :search, :on => :collection
      member do
        post :updateAvatar
        post :updateOwnership
        patch :num_incompleted_tasks
        get :complete_users
        get :crop
        get :setCoord
      end
    end

    resources :notification_settings

    resources :tasks do
      resources :t_blockers, :controller => 'tasks', :defaults => {:type => 'blocker'}, :name_prefix => "tasks_"
      member do
        patch :add_deadline
        patch :delete_deadline
        patch :complete
        patch :incomplete
        patch :changelist
        patch :changeuser
        patch :importanttask
      end
    end

    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]
    mount ActionCable.server, at: '/cable'

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include LoginHelper
  include ApplicationHelper
  skip_before_action :verify_authenticity_token
  before_action :require_logged_in, :except => [:showList_blocker]
  # before_action :current_date,  if: -> { !params[:date].blank? }
  before_action :set_user, only: [:show, :edit, :update, :destroy, :updateOwnership, :create]
  before_action :set_list, only: [:index, :show, :create, :showList, :edit, :update, :updateAvatar, :destroy, :complete_users, :search, :showList_blocker, :updateOwnership, :setCoord, :crop]
  before_action :validate_ownership_update, only: [:updateOwnership]

  def index
    @all_tasks = current_user.tasks.where(:completed_at => nil).order('created_at')
    @lists = current_user.created_lists.where("name not null").order('created_at')
    @collaboration_lists = current_user.collaboration_lists.where("name not null")
    # @created_lists =
    respond_to do |format|
      format.html{}
      format.json
      format.js
    end

  end

  def search
    # result = User.connection.select_all("SELECT  'users'.* FROM 'users' INNER JOIN 'collaborations' ON 'users'.'id' = 'collaborations'.'user_id' WHERE 'collaborations'.'list_id' = #{@list.id} UNION SELECT  'users'.* FROM 'users' INNER JOIN 'lists' ON 'users'.'id' = 'lists'.'user_id' WHERE 'lists'.'id' = #{@list.id}")
    @collaboration_users = @list.collaboration_users
    user = User.where('id'=> params[:user_id])
    owner  =  User.where('id' => @list.user_id)
    @users_mention = @collaboration_users.search(params[:term]) + owner.search(params[:term]) -  user.search(params[:term])

    @result = @users_mention
    # if user.id != @list.user_id
    #   owner  =  User.where('id' => @list.user_id)
    #   @users_mention = @collaboration_users.search(params[:term]) + owner.search(params[:term])
    #   @result =  @users_mention
    # else
    #   @result = @collaboration_users.search(params[:term])
    # end

    respond_to do |format|
      format.html
      format.json { @result }
      format.js
    end
  end

  def show
    if !params[:mention_by].blank?
      mention_by = params[:mention_by].tr('[]', '').split(',').map(&:to_i)
      @collaboration_users = User.where(id: mention_by)
    end
    gon.startDate = startDate
    respond_to do |format|
      format.html { redirect_to root_path}
      format.json { render json: @list }
      format.js
    end

  end

  def showList
    respond_to do |format|
      format.html{ render layout: 'modal'}
      format.json
      format.js
    end
  end


  def showList_blocker
    @user = User.find_by_email(params[:email].downcase)
    unless current_user?(@user.id)
      @collaborator = User.find(params[:mention_by])
      respond_to do |format|
        format.html {redirect_to root_path }
        format.json { render json: @list }
        format.js
      end
    else
      flash[:danger] = "You need to login as #{params[:email]}."
      redirect_to root_path
    end

  end

  def complete_users
    @collaboration_users = @list.collaboration_users
    @c_users = {}
    @collaboration_users.each do |user|
      @c_users['value'] =   user.id
      @c_users['label'] =   user.first_name
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @list = current_user.created_lists.build
    render layout: 'modal'

  end

  def edit
    @pending_invitations = @list.pending_invitation
    respond_to do |format|
      format.html { render layout: 'modal'}
      format.js
    end
  end

  def create
    @list = current_user.created_lists.build(list_params)
    @list.crop_x = list_params[:crop_x]
    @list.crop_y = list_params[:crop_y]
    @list.crop_w = list_params[:crop_w]
    @list.crop_h = list_params[:crop_h]
    # @list.skip_validation = false
    if @list.save
      flash[:notice] = "List was successfully created."
      @_current_list = session[:list_id] = List.current = nil
      session[:list_id] = @list.id
      gon.startDate = startDate
      session[:active_collaborations] = Array.new
      session[:active_collaborations][0] = current_user.id
      html = ListsController.render(partial: "lists/nav_list_name",  layout: "layouts/li_navigation", locals: {"list": @list, "user": @list.owner, "active": true}).squish
      respond_to do |format|
        format.json { render :json => {:list => @list, :html=> html,:status => 'success', :flash => flash[:notice] }}
      end
      # redirect_to root_path(@list)

    else
      # flash[:danger] = "We can't create the list."
      @htmlerrors = ListsController.render(partial: "shared/error_messages", locals: {"object": @list}).squish
      # render "new", layout: 'modal'
      render :json => {:status => 'fail',:htmlerrors => @htmlerrors, :errors => @list.errors }
      # render :json => {:status => 'fail', :errors => @list.errors.full_messages}

    end
  end

  def updateAvatar
    if list_params[:image].present?
      @list.current_step = 'avatar'
      @list.skip_validation = true
      if @list.update_attributes(image: list_params[:image])
        flash[:notice] = "Avatar updated"
        respond_to do |format|
          format.html { render 'crop'}
          format.js
        end

      end
    else
      render :json => {:status => 'fail', :errors => @list.errors.full_messages}
    end

  end

  def update
    gon.list = @list
    @list.crop_x = list_params[:crop_x]
    @list.crop_y = list_params[:crop_y]
    @list.crop_w = list_params[:crop_w]
    @list.crop_h = list_params[:crop_h]
    saved = (@list.all_tasks_list?) ? @list.update_attributes(:description => list_params[:description]) : @list.update_attributes(list_params)
    respond_to do |format|
      if saved
          flash[:notice] = "List was successfully updated."
          format.json { render :json => {:list => @list,:status => 'success', :flash => flash[:notice] }}
      else
          flash[:danger] = "We can't update the list."
          @htmlerrors = ListsController.render(partial: "shared/error_messages", locals: {"object": @list}).squish
          format.json { render :json => {:status => 'fail',:htmlerrors => @htmlerrors, :errors => @list.errors }}
        end
    end
  end

  def updateOwnership
    authorize @list
    @new_owner = User.find(params[:new_list_owner].to_i)
    @new_owner.collaboration_lists.delete(@list)
    if @invitation = @new_owner.invitations.find_by(list_id: @list.id)
      @invitation.delete
    end
    @list.owner = @new_owner
    @list.save
    @user.collaboration_lists << @list
    @collaboration = Collaboration.find_by(list_id: @list.id, user_id: @user.id)
    @collaboration.update_attributes(:collaboration_date => Time.now)
    flash[:notice] = "Ownership updated"
    redirect_to root_path(@list)

  end

  def crop
    render layout: 'popupcrop'
  end

  def setCoord
    @list.crop_x = list_params[:crop_x]  #params[:user][:crop_x]
    @list.crop_y = list_params[:crop_y] #params[:user][:crop_y]
    @list.crop_w = list_params[:crop_w] #params[:user][:crop_w]
    @list.crop_h = list_params[:crop_h] #params[:user][:crop_h]
    @list.skip_validation = true
    if @list.save!
      respond_to do |format|
        flash[:notice] = "Avatar updated"
        # format.html {  }
        format.js {  }
      end
    end
  end


  def destroy
    if @list.destroy

      session[:list_id] = List.current = nil
      @list = session[:list_id] = List.current = @user.all_task

      flash[:notice] = "List was successfully destroyed."
      # redirect_to root_path(@list)
      respond_to do |format|
        format.html { }
        format.js { render :action => "show"}
      end
    end
  end

  private

  def set_list
    if params[:id].blank?
      @list = List.current =current_list
    else
      @list = List.find(params[:id])
      @_current_list = session[:list_id] = List.current = nil
      session[:list_id] = params[:id]
      @_current_list = List.current = @list
      session[:active_collaborations] = Array.new
      session[:active_collaborations][0] = current_user.id
      set_current_list
    end
    @active_users = active_collaborator(@list)
  end

  def set_user
    if params[:user_id].blank?
      @user = current_user
    else
      @user = User.find(params[:user_id])
    end
  end


  def validate_ownership_update
    user = current_user
    @new_owner_id = params[:list_owner].to_i
    @current_password = params[:current_password]

    numberoferror = 0
    if @new_owner_id.blank?
      @list.errors.add(:new_list_owner,message: "New Owner cannot be blank.")
      numberoferror += 1
    end

    if  @new_owner_id == current_user.id
      @list.errors.add(:new_email,message: "Current Owner and New owner cannot be the same.")
      numberoferror += 1
    end

    if @current_password.blank?
      @list.errors.add(:password, message: "Password cannot be blank.")
      numberoferror += 1
    end

    if !user.authenticate(@current_password)
      @list.errors.add(:password, message: "Password incorrect.")
      numberoferror += 1
    end

    if numberoferror != 0
      respond_to do |format|
        format.json { render json: { status: 'invalid',:errors => @list.errors.messages }, status: :bad_request}
        format.js { render :action => "edit" }
      end
    end
  end

  # def set_task_per_user
  #   d_today = get_current_date
  #   d_yesterday =  d_today - 1.day
  #   incomplete_tasks = @list.incompleted_tasks(@user)
  #   @incomplete_tasks = incomplete_tasks.where(["DATE(created_at)=?",d_today])
  #   byebug
  #   @incomplete_tasks_past= (Date.today == d_today)? incomplete_tasks - @incomplete_tasks : nil
  #   # @incomplete_tasks_past = incomplete_tasks - @incomplete_tasks
  #   # @list.incompleted_tasks(@user).where(["DATE(created_at)<?",d_today])
  #   # @incomplete_tasks = @tasks.where(["completed_at IS ? and DATE(created_at)=?",nil,d_today])

app/helpers/lists_helper.rb
module ListsHelper
  # def owner?(list)
  #   list.owner == User.current
  # end

  def has_collaborations?(list)
    !list.collaboration_users.empty?
  end

  def collaboration_users(list)
    # byebug
    collaboration = list.collaboration_users.where.not(:id=> User.current.id)
    if !current_user.owner?(list)
      collaboration.merge(list.owner)
    end
    @collaboration_users = collaboration

  end

  def all_task?(id)
    
    List.find(id).all_tasks
  end

end

app/views/lists/_collaboration_user.html.erb
<% if (!collaboration_user.blank?) %>
  <%  if ((!collaboration_user.active_collaborator?(current_list.id) && current_user.owner?(current_list)) || collaboration_user.active_collaborator?(current_list.id))%>
      <% active = "" %>
      <% if (active_users.count!=0) %>
          <% active = (active_users.include?(collaboration_user)) ? "active" : "" %>
      <% end %>
      <% msinactive =  !collaboration_user.active_collaborator?(current_list.id)? "ms-inactive" : "" %>
      <%= content_tag :li, class: " #{(collaboration_user.id == current_user.id)? "active ms-current-user" : active} #{msinactive} #{(collaboration_user.id == current_user.id)? 'disabled': ''}" , id: "collaboration_user_#{collaboration_user.id}", data: {:'chip-user-id'=> "#{collaboration_user.id}"} do%>
        <% if (collaboration_user.id == current_user.id)%>
            <% if !collaboration_user.image.blank? %>
               <span class="member-avatar avatar-online">
                  <%= image_tag(collaboration_user.image_url(:thumb), class: 'circle') %>
               </span>
            <% else %>
               <span class="user-initial circle"><%= initials(collaboration_user.id) %></span>
            <% end %>
        <% else %>
            <%= link_to list_collaboration_user_path(current_list,collaboration_user),class: "tooltipped", id:"#{collaboration_user.id}",remote: true,:data => { :'tooltip'=>"Show tasks for #{collaboration_user.first_name}" }  do %>
                <% if !collaboration_user.image.blank? %>
                    <span class="member-avatar avatar-online">
                       <%= image_tag(collaboration_user.image_url(:thumb), class: 'circle') %>
                       <!-- <img src="equilateral.png" alt="triangle with equal sides" srcset="equilateral.svg"> -->
                    </span>
                <% else %>
                   <span class="user-initial circle"><%= initials(collaboration_user.id) %></span>
                <% end %>
            <% end %>
        <% end %>
      <% end %>
  <% end %>
<% end %>

app/views/lists/_formDate.html.erb
<%= form_for "formDate",@list, method: :get,remote: true do |f| %>
<!-- <input type="hidden" name="date"> -->
  <input type="date" class="datepicker" name="date">
<% end %>

app/views/lists/_li_nav_list.html.erb
<li class="bold <%= (list.id == listCurrent.id )? 'active' : '' %>" data-name="<%=list.name %>" data-nav-list-id="<%=list.id %>">
  <a id="<%= list.id %>" href="#" data-href= "<%=list_path(list) %>" data-remote="true">
      <%= render partial: "lists/nav_list_name", locals: {list: list} %>
      <div class="right">
        <% if list.collaborations? %>
            <i class="material-icons bar-collaboration-icon">group</i>
        <% end %>
        <span class="bar-number-task"><%= user.num_incompleted_tasks(list)%></span>
     </div>
  </a>
</li>

app/views/lists/_link_listSetting.html.erb
  <!-- <%= link_to (user.owner?(list))? edit_list_path(list) : list_showList_path(list), data: { behavior: 'modal' },remote: true do%>
     <i class="material-icons md-15 md-light">settings</i>
  <% end %> -->
  <% if policy(list).update? %>
    <%= link_to edit_list_path(list), data: { behavior: 'modal' },remote: true do%>
       <i class="material-icons md-15 md-light">settings</i>
    <% end %>
  <% end %>

app/views/lists/_list.html.erb
<%= content_tag :div, data: {"list-id": "#{list.id}"}, id: "current-list" do%>
    <section class="center row">
      <div class="col s12">
        <% unless (list.all_tasks?) %>
            <div class="share-icons">
                <div class="list-collaboration-users">
                    <div class="right">
                        <%= content_tag :ul, id: "collaboration-users", class: "sort_c_users", data: {"url" => "#{sort_list_collaboration_users_path(list)}"} do%>
                              <% if has_collaborations?(list) %>
                                  <% if  list.collaboration_users.where(['user_id != ?', current_user.id]).count > 0 %>
                                     <%= render partial: "lists/collaboration_user", collection: list.collaboration_users.where(['user_id != ?', user.id]).order('position ASC'), as: :collaboration_user, locals: { active_users: active_users,current_user: user }%>
                                  <% end %>
                              <% end %>
                              <%= render partial: "lists/collaboration_user", locals: {collaboration_user: list.owner, active_users: active_users, current_user: user} %>
                              <%= render partial: "lists/collaboration_user", locals: {collaboration_user: user, active_users: active_users, current_user: user} if !user.owner?(list)%>
                        <% end %>
                        <ul id="collaboration-menu">
                          <% if has_collaborations?(list) %>
                              <li class="ms-view-all">
                                <%= link_to list_collaboration_users_path(list),id: 'show_all_collaborators',class:"tooltipped", data: {behavior: 'modal', tooltip: 'Show all members', remote: true} do%>
                                    <span class="circle-icon valign-wrapper">
                                      <% if active_users.empty? %>
                                              <%= image_tag(asset_path('assets/showAll.svg',skip_pipeline: true)) %>
                                        <% else%>
                                          <%= (active_users.count >= list.collaboration_users.count)? image_tag(asset_path('assets/hideAll.svg',skip_pipeline: true)) : image_tag(asset_path('assets/showAll.svg',skip_pipeline: true)) %>
                                        <%end%>
                                    </span>
                                <% end %>
                              </li>
                          <% end %>
                          <% if (current_user.owner?(list)) %>
                              <li class="ms-add">
                                <%= link_to new_list_invitation_path(list),id: 'new_invitation_link',class:"tooltipped", data: {behavior: 'modal', tooltip: 'Invite a new member', remote: true} do%>
                                    <span class="circle-icon valign-wrapper">
                                        <%= image_tag(asset_path('assets/adduser.svg',skip_pipeline: true)) %>
                                    </span>
                                <% end %>
                              </li>
                          <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        <% end %>
      </div>
    </section>
    <!--  SECTION LIST USERS -->
    <section id="list-users">
      <ul>
        <%= render partial: "users/list_user", locals: {user: user, list: list} %>
      </ul>
      <%= content_tag :ul, class: "sort_c_users", data: {"url" => "#{sort_list_collaboration_users_path(list)}"} do%>
        <%= render partial: "users/list_user", collection: active_users.without(user), as: :user, locals: { list: list } if (!active_users.blank? ) %>
      <% end %>
    </section>
    <!--  END SECTION LIST USERS -->
<% end %>

app/views/lists/index.html.erb
<%= render partial: "list", locals: { list: current_list, user: current_user } %>

app/views/lists/new.js.erb
<% if @list.errors.any? %>
    <% @list.errors.messages.each do |key,value| %>
          $("#form_list input[name*='list[<%= key %>]']").addClass("invalid");
    <% end %>
    $("#error_message_list").html("<%= j render :partial => 'shared/error_messages', :locals => {:object => @list} %>");
<% else %>

  $("#error_message").html("<%= j render :partial => 'shared/flash_messages', :locals => {:object => @list} %>");

  // var $content = $('#page-content #main_center'),
  //     $form =  $('#application-date form'),
  //     $nav = $('[data-nav-id = "<%#= @user.id%>"]'),
  //     $ulCreated = $('ul#ulCreated', $nav),
  //     $add = $("#ms-add", $ulCreated);
  //
  // // $content.html("<%#= j render partial: 'lists/list', locals: { list: @list, user: @user, collaboration_users: [] } %>");
  //
  // droppable_all('li[id^="drop_zone_"]');
  //
  // $("#ms-link-listSetting").html("<%#= j render partial: 'lists/link_listSetting', locals:{list: @list} %>");
  //
  // $form.attr("action","lists/<%#= @list.id %>");
  // $form.attr("id","edit_list_<%#= @list.id %>");
  //
  // $("li", $ulCreated ).removeClass('active');
  //
  // $('.edit_task').submitOnCheck();
  // dropdown("[id^=dropdown_list_]","false");
  //
  // $('#nav-list').html("<%#= j render partial: 'lists/nav_list_name', locals: {list: @list} %>");
  // $("<%#= j render partial: 'lists/nav_list_name', layout: 'layouts/li_navigation', locals: {'list': @list, 'user': current_user, 'active': 'active'} %>").insertBefore($add);
  // $('#nav-list').attr( "data-topnavbar-list-id", "<%= @list.id %>" );
  // $('#application-date .datepicker').pickadate({
  //     disable: [
  //       { from: [0,0,0], to: gon.startDate }
  //     ]
  //   });

<% end %>

app/views/lists/search.html.erb
<article class="app-cont">

  <section class="app-title cf">
    <h1>User 1</h1>

  </section>

  <!-- <section class="app-content">
    <div class="users-search">
      <input type="hidden" id="users-search-hidden">
      <input type="text" id="users-search-txt" autofocus>
      <div class="results" id="users-search-results"></div>
      <input type="text" id="tags" autofocus>
     </div>
  </section> -->
  <div>
      <input type="text" id="inputor">
      <button id="btn-inputor">Value</button>
  </div>

  <div id="inputor1" contentEditable="true">hello!</div>

</article>

<%= javascript_tag do %>

$(function() {

    <!-- new app.Users; -->

    /**** Tag user *****/
    var availableTags = [
        "ActionScript",
        "AppleScript",
        "Asp",
        "BASIC",
        "C",
        "C++",
        "Clojure",
        "COBOL",
        "ColdFusion",
        "Erlang",
        "Fortran",
        "Groovy",
        "Haskell",
        "Java",
        "JavaScript",
        "Lisp",
        "Perl",
        "PHP",
        "Python",
        "Ruby",
        "Scala",
        "Scheme"
        ];

    function split(val) {
        return val.split(/@\s*/);
    }

    function extractLast(term) {
        return split(term).pop();
    }

     $("#tags")
     .bind("keydown", function(event) {
         if (event.keyCode === $.ui.keyCode.TAB && $(this).data("autocomplete").menu.active) {
             event.preventDefault();
         }
     }).autocomplete({
         minLength: 0,
         source: function(request, response) {
             var term = request.term,
                 results = [];
             console.log(term);
             if (term.indexOf("@") >= 0) {
                 term = extractLast(request.term);
                 if (term.length > 0) {
                   console.log("/lists/search?term="+term);
                   $.ajax({
                          url: "/lists/search?term="+term,
                          dataType: "json",
                          success: function( data ) {
                            console.log(data[0].label);
                            results = data[0].name;

                              }
                          });
                 } else {
                     results = ['Start typing...'];
                 }
             }
             response(results);
         },
         focus: function() {
             // prevent value inserted on focus
             return false;
         },
         select: function(event, ui) {
           var terms = split(this.value);
             // remove the current input
             terms.pop();
             // add the selected item
             terms.push(ui.item.value);
             // add placeholder to get the comma-and-space at the end
             terms.push("");
             this.value = terms.join("");
             return false;
         }
     });
    /*** end tag user ****/

  });


  /*** end tag user ****/



<% end %>

app/views/lists/show.js.erb
$('#ms-modal-dialog').modal("close");
var $form =  $('#application-date form'),
    $content = $('#page-content #main_center'),
    $nav = $('[data-nav-id = "<%=@user.id%>"]'),
    $ulCreated = $('ul#ulCreated', $nav);


$("li", $ulCreated ).removeClass('ui-droppable-disabled');

if($('#new-list').length){
  $('#new-list').remove();
}
if($('#ms-user-edit').length){
  $('#ms-user-edit').remove();
}
if($('#ms-user-nav-setting').length){    //#ms-tabsSetting
  $('#ms-user-nav-setting').remove();   //#ms-tabsSetting
}
if ($('body').hasClass('expand-header')){
  $('body').removeClass('expand-header');
  $('.nav-main ul.right').removeClass('hide');
}

$content.html("<%= j render partial: 'lists/list', locals: { list: @list, user: @user, active_users: @active_users } %>");
droppable_all('li[id^="drop_zone_"]');

if (!$('[data-nav-list-id= "<%=@list.id%>"]', $nav).hasClass('active')){
  $('[data-nav-list-id= "<%=@list.id%>"]', $nav).addClass('active');
}

$("#ms-link-listSetting").html("<%= j render partial: 'lists/link_listSetting', locals:{list: @list, user: @user} %>");

$form.attr("action","lists/<%= @list.id %>");
$form.attr("id","edit_list_<%= @list.id %>");
$('.edit_task').submitOnCheck();
dropdown("[id^=dropdown_list_]","false");
msCollapsible("collapsible");


$('#nav-list').html("<%= j render partial: 'lists/nav_list_name', locals: {list: @list} %>");
svg();
$('.nav-main li.avatar-list').hasClass('avatar-user').removeClass('avatar-user');
$('#nav-list').attr( "data-topnavbar-list-id", "<%= @list.id %>" );
sortableCollaborationUsers($('.sort_c_users'));

$('.tooltipped').tooltip({delay: 50});

$('#application-date .datepicker').pickadate({
  disable: [
    { from: [0,0,0], to: gon.startDate }
  ]
});

app/views/lists/showList.html.erb
<div class="valign-wrapper ms-upload-avatar" style="<% if (!@list.new_record?) %>background-image: url('<%= @list.image_url('thumb') %>');<% end %>">
</div>
<div class="input-field">
  List Name: <%= @list.name.capitalize %>
</div>
<div class="input-field">
  List Description: <%= (!@list.description.present?) ? "No Description" : @list.description%>
</div>
<div class="input-field">
  List Owner: <% unless @list.owner.nil? %><%= "#{@list.owner.first_name.capitalize} #{@list.owner.last_name.capitalize}" %> <% end%>
</div>
<div class="divider"></div>
<div class="row">
	<div class="col s6">
	</div>
  <div class="col s6">
    <div class="input-field center-align">
    </div>
  </div>
</div>

app/views/lists/showList_blocker.js.erb
// $(document).on('turbolinks:load',function(){
    var $form =  $('#application-date form');
    var $content = $('#page-content #main_center');
    if($('#new-list').length){
      $('#new-list').remove();
    }
    if($('#ms-user-edit').length){
      $('#ms-user-edit').remove();
    }
    if($('#ms-tabsSetting').length){
        $('#ms-tabsSetting').remove();
    }
    if ($('body').hasClass('expand-header')){
        $('body').removeClass('expand-header');
    }

    $content.html("<%= j render partial: 'lists/list', locals: { list: @list, user: current_user } %>");

    $("#ms-link-listSetting").html("<%= j render partial: 'lists/link_listSetting', locals:{list: @list} %>");

    $form.attr("action","lists/<%= @list.id %>");
    $form.attr("id","edit_list_<%= @list.id %>");
    $('.edit_task').submitOnCheck();

    $('#nav-list').html("<%= j render partial: 'lists/nav_list_name', locals: {list: @list} %>");
    $('#nav-list').attr( "data-topnavbar-list-id", "<%= @list.id %>" );

    $('.tooltipped').tooltip({delay: 50});

    var $list = $('[data-list-id = "<%= @list.id %>"]');
    var $listUsers = $('#list-users',$list);
    var $collaboration_user = $('#collaboration-users li#<%= @collaborator.id %>',$list);

    $collaboration_user.addClass('active');
    $listUsers.append("<%= j render partial: 'users/list_user', locals:{user: @collaborator, list: @list } %>");
    var $user = $('[data-user-id = "<%= @collaborator.id %>"]',$list);
    $('input[id="task_user_id"]',$user).val("<%= @colaborator.id %>");
    $('.tooltipped').tooltip({delay: 50});

    $('.edit_task').submitOnCheck();
    deadlineDatepicker($('input.deadline-datepicker'));
    $('input.deadline-datepicker.hidden-datepicker').hover(handlerIn, handlerOut);
  // })