config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

    root 'home#dashboard'
    mount Sidekiq::Web, at: '/sidekiq'

    get 'password_resets/new'

    get 'password_resets/edit'
    get 'password_resets' => 'password_resets#new'
    get 'login/create'

    get 'login/destroy'
    get '/new' => 'users#new', :as => 'sign_up'

    get '/login' => 'login#new'
    post '/login' => 'login#create'
    get '/logout' => 'login#destroy'
    get '/confirmation_page' => 'login#confirmation'
    get '/lists/:id/showList' => 'lists#showList', as: 'list_showList'
    get '/lists/:id/showList_blocker' => 'lists#showList_blocker', as: 'showList_blocker'
    get '/task/:id/showTask' => 'tasks#showTask', as: 'showTask'

    post 'users/resend_activation' => 'users#resend_activation'

    resources :notifications do
      collection do
        post :mark_as_read
      end
    end
    resources :sessions
    resources :users do
      resources :lists, :name_prefix => "user_"
      member do
        post :updateAvatar
        post :updateEmail
        post :updatePassword
        get :settings
        get :notifications
        get :crop
        get :setCoord
        get :showCompletedTask
      end
    end

    resources :lists do
      resources :tasks, :name_prefix => "list_" do
        put :sort, on: :collection
      end
      resources :invitations do
        member do
          get :resend_invitation
        end
      end
      resources :collaboration_users, :controller => 'users', :defaults => {:type => 'collaborator'} do
        put :sort, on: :collection
      end
      get :search, :on => :collection
      member do
        post :updateAvatar
        post :updateOwnership
        patch :num_incompleted_tasks
        get :complete_users
        get :crop
        get :setCoord
      end
    end

    resources :notification_settings

    resources :tasks do
      resources :t_blockers, :controller => 'tasks', :defaults => {:type => 'blocker'}, :name_prefix => "tasks_"
      member do
        patch :add_deadline
        patch :delete_deadline
        patch :complete
        patch :incomplete
        patch :changelist
        patch :changeuser
        patch :importanttask
      end
    end

    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]
    mount ActionCable.server, at: '/cable'

end

app/models/blocker.rb
class Blocker < ApplicationRecord
  belongs_to :user, validate: true

  validates_uniqueness_of :user_id, scope: [:session_id]

end

app/controllers/blockers_controller.rb
class BlockersController < ApplicationController
  include ApplicationHelper
  # before_filter :get_session, only: [:show]
  before_action :require_logged_in
  before_action :set_blocker, only: [:show, :edit, :update, :destroy]
  # before_filter :get_session, only: [:edit, :update]

  def get_session
    @session = Session.find(@blocker.session_id)
  end

  # GET /blockers
  # GET /blockers.json
  def index
    @blockers = Blocker.all
  end

  # GET /blockers/1
  # GET /blockers/1.json
  def show
    # @blockers = @session.blockers
  end


  # GET /blockers/new
  def new
    @blocker = user.blocker.new
  end

  # GET /blockers/1/edit
  def edit
  end

  # POST /blockers
  # POST /blockers.json
  def create
    @blocker = user.blocker.new(blocker_params)
    @team = Team.find(session[:team_id])
    @users = Session.get_users(params[:user_ids].map{|i| i.to_i})
    @session.tag_list = get_user_first_names(@users)
    respond_to do |format|
      if @blocker.save
        format.html { redirect_to @blocker, notice: 'Blocker was successfully created.' }
        format.json { render :show, status: :created, location: @blocker }
      else
        format.html { render :new }
        format.json { render json: @blocker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blockers/1
  # PATCH/PUT /blockers/1.json
  def update
    blocker_item = params[:content]
    respond_to do |format|
      if @blocker.update(blocker: blocker_item)
        format.html { redirect_to @session, notice: 'Blocker was successfully updated.' }
        format.json { render :show, status: :ok, location: @session }
        format.js {render :nothing => true, notice: 'Wip was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @blocker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blockers/1
  # DELETE /blockers/1.json
  def destroy
    @blocker.destroy
    respond_to do |format|
      format.html { redirect_to blockers_url, notice: 'Blocker was successfully destroyed.' }
      format.json { head :no_content }
      Blocker.reset_pk_sequence
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blocker
      @blocker = Blocker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blocker_params
      params.require(:blocker).permit(:session_id, :user_id, :blocker)
    end
end

app/helpers/blockers_helper.rb
module BlockersHelper
end

app/views/blockers/_form.html.erb
<%= form_for blocker, remote: true do |f| %>
  <% if blocker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blocker.errors.count, "error") %> prohibited this blocker from being saved:</h2>

      <ul>
      <% blocker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag "blocker.png", :size => "15x15" %>
    <%= f.label :blocker %><br>
    <%= f.text_area :blocker %>
    <%= f.text_field :tag_list %>
  </div>
  <!-- <div class="">
    <%#= f.submit %>
  </div> -->
<% end %>

app/views/blockers/edit.html.erb
<h1>Editing Blocker</h1>

<%= render 'form' %>

<%= link_to 'User', user_path(@blocker.user_id) %> |
<%= link_to 'Back to Session', session_path(@blocker.session_id) %>

app/views/blockers/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "Listing Blockers for Session" %></h1>

<table>
  <thead>
    <tr>
      <th>Session</th>
      <th>User</th>
      <th>Blocker</th>
      <th>Blocker id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blockers.each do |blocker| %>
      <tr>
        <td><%= blocker.session_id %></td>
        <td><%= blocker.user_id %></td>
        <td><%= blocker.blocker %></td>
        <td><%= blocker.id %></td>
        <td><%= link_to 'Show', sessions_path %></td>
        <td><%= link_to 'Edit', edit_blocker_path(blocker) %></td>
        <td><%= link_to 'Destroy', blocker, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blocker', new_blocker_path %>

app/views/blockers/new.html.erb
<h1>New Blocker</h1>

<%= render 'form' %>

<%= link_to 'Back', blockers_path %>

app/views/blockers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Session:</strong>
  <%= @blocker.session_id %>
</p>
<p>
  <strong>User:</strong>
  <%= @blocker.user_id %>
</p>
<p>
  <strong>Blocker:</strong>
  <%= @blocker.blocker %>
</p>

<%= link_to 'Edit', edit_blocker_path(@blocker) %> |
<%= link_to 'Back to Session', session_path(@blocker.session_id) %>