config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

    root 'home#dashboard'
    mount Sidekiq::Web, at: '/sidekiq'

    get 'password_resets/new'

    get 'password_resets/edit'
    get 'password_resets' => 'password_resets#new'
    get 'login/create'

    get 'login/destroy'
    get '/new' => 'users#new', :as => 'sign_up'

    get '/login' => 'login#new'
    post '/login' => 'login#create'
    get '/logout' => 'login#destroy'
    get '/confirmation_page' => 'login#confirmation'
    get '/lists/:id/showList' => 'lists#showList', as: 'list_showList'
    get '/lists/:id/showList_blocker' => 'lists#showList_blocker', as: 'showList_blocker'
    get '/task/:id/showTask' => 'tasks#showTask', as: 'showTask'

    post 'users/resend_activation' => 'users#resend_activation'

    resources :notifications do
      collection do
        post :mark_as_read
      end
    end
    resources :sessions
    resources :users do
      resources :lists, :name_prefix => "user_"
      member do
        post :updateAvatar
        post :updateEmail
        post :updatePassword
        get :settings
        get :notifications
        get :crop
        get :setCoord
        get :showCompletedTask
      end
    end

    resources :lists do
      resources :tasks, :name_prefix => "list_" do
        put :sort, on: :collection
      end
      resources :invitations do
        member do
          get :resend_invitation
        end
      end
      resources :collaboration_users, :controller => 'users', :defaults => {:type => 'collaborator'} do
        put :sort, on: :collection
      end
      get :search, :on => :collection
      member do
        post :updateAvatar
        post :updateOwnership
        patch :num_incompleted_tasks
        get :complete_users
        get :crop
        get :setCoord
      end
    end

    resources :notification_settings

    resources :tasks do
      resources :t_blockers, :controller => 'tasks', :defaults => {:type => 'blocker'}, :name_prefix => "tasks_"
      member do
        patch :add_deadline
        patch :delete_deadline
        patch :complete
        patch :incomplete
        patch :changelist
        patch :changeuser
        patch :importanttask
      end
    end

    resources :account_activations, only: [:edit]

    resources :password_resets, only: [:new, :create, :edit, :update]
    mount ActionCable.server, at: '/cable'

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # autocomplete :user, :first_name
  include TasksHelper
  include UsersHelper
  include ApplicationHelper
  include LoginHelper
  before_action :require_logged_in
  before_action :set_task,  if: -> { !params[:type].blank? || !params[:id].blank? }
  before_action :set_user, only: [:create, :index ]
  before_action :set_current_list, :except => [:changelist]
  before_action :saved_list, only: [:changelist, :update, :complete ]


  def new
    if (params[:type].present? || params[:type]=="blocker")
      @t_blocker = @task.t_blockers.build
    else
      @task = current_list.tasks.build
    end
    render layout: 'modal'
  end

  def edit
    render layout: 'modal'
  end

  def create
    #  authorize @task
    if params[:type].present?
      @t_blocker = @task.t_blockers.build(task_params)
      @t_blocker.current_user_id = current_user.id
      if @t_blocker.save
        tag_emails = @t_blocker.mention_emails
        sender = current_user
        notification_type = notification_type("tagged")
        # tag_emails.each do |email|
        #   email.sub!(/^+/, '')
        #   recipient = User.find_by_email(email)
        #   TaskMailer.mentioned_in_blocker(email, sender, @t_blocker).deliver_now if (notification_active?(recipient, notification_type,1))
        #   Notification.create(recipient:recipient, actor:sender, notification_type: notification_type, notifiable: @t_blocker) if (notification_active?(recipient, notification_type,2))
        #  end
        mentioned_in(tag_emails, @t_blocker, notification_type, sender)
        flash[:success] = "Blocker created"
      end
    else
      @task = current_list.tasks.build(task_params)
      List.current = nil
      @list = List.current = current_list
      @task.current_user_id = current_user.id
      if @task.save
        tag_emails = @task.mention_emails
        sender = current_user
        notification_type = notification_type("tagged")
        mentioned_in(tag_emails, @task, notification_type, sender)

        if (!current_user?(@task.user_id))
          recipient = @task.user
          notification_type= notification_type("assigned")
          Notification.create(recipient: recipient, actor:current_user, notification_type: notification_type,notifiable: @task) if (notification_active?(recipient, notification_type,2))
        end
        flash[:success] = "Task created"
      end
    end
  end

  def update
    authorize @task
    if (@task.update_attributes!(task_params))
      sender = current_user
      notification_type = notification_type("tagged")
      tag_emails = @task.mention_emails
      mentioned_in(tag_emails, @task, notification_type, sender)
      flash[:notice] = 'Updated'
      # tag_emails.each do |email|
      #    recipient = User.find_by_email(email)
      #    Notification.create(recipient: recipient, actor:sender, notification_type: notification_type,notifiable: @task) if (notification_active?(recipient, notification_type,2))
      #    TaskMailer.mentioned_in_blocker(email, sender,@task).deliver_now if (notification_active?(recipient, notification_type,1))
      #  end
      if @task.is_blocker?
        # tag_emails = params['tags_emails'].split(',')
        # tag_emails = @task.mention_emails
        # tag_emails.each do |email|
        #    recipient = User.find_by_email(email)
        #    notification_type = notification_type("tagged")
        #    Notification.create(recipient: recipient, actor:sender, notification_type: notification_type,notifiable: @task) if (notification_active?(recipient, notification_type,2))
        #    TaskMailer.mentioned_in_blocker(email, sender,@task).deliver_now if (notification_active?(recipient, notification_type,1))
        #  end
      elsif (@task.previous_changes.key?(:detail) && @task.previous_changes[:detail].first != @task.previous_changes[:detail].last)
        @task.detail_before = @task.previous_changes[:detail].first

        if (!(current_user?(@task.assigner_id))&&(@task.assigner_id != @task.user.id ))
          recipient = (@task.assigner_id != @task.user.id ) ? User.find_by(id: @task.assigner_id) : @task.user
          notification_type = notification_type("updated")
          # TaskMailer.mentioned_in_blocker(email, sender,@task).deliver_now if (notification_active?(recipient, notification_type,1))
          if !recipient.blank?
            Notification.create(recipient: recipient, actor: sender, notification_type: notification_type, notifiable: @task) if (notification_active?(recipient, notification_type,2))
          end
        end
      end
    end
  end

  def add_deadline
    if (!params[:deadline].blank?) && (!params[:deadline].nil?) && (params[:deadline] != "null")
      authorize @task
      if @task.update_attribute(:deadline, params[:deadline])
        sender = current_user
        if (!current_user?(@task.user_id))
          recipient = @task.user
          notification_type = notification_type("deadline")
          # TaskMailer.mentioned_in_blocker(email, sender,@task).deliver_now if (notification_active?(recipient, notification_type,1))
          Notification.create(recipient:@task.user, actor:current_user, notifiable: @task, notification_type: notification_type) if (notification_active?(recipient, notification_type,2))
        end
        flash[:notice]= 'Deadline was added'
      end
    end
  end

  def delete_deadline
    if @task.update_attribute(:deadline, '')
      List.current = current_list
      if (!current_user?(@task.user_id))
        notification_type = notification_type("deadline")
        recipient = @task.user
        # TaskMailer.mentioned_in_blocker(email, sender,@task).deliver_now if (notification_active?(recipient, notification_type,1))
        Notification.create(recipient:recipient, actor:current_user, notifiable: @task,notification_type: notification_type) if (notification_active?(recipient, notification_type,2))
      end
      flash[:notice]= 'Deadline date was removed'
    else
      flash[:notice]= 'We were unable to delete deadline, try later'
    end
  end

  def importanttask
    authorize @task
    @task.toggle! :flag
    flash[:notice] = "Task was correctily updated"
  end

  def destroy
    if !@task.blank?
      currentUser = current_user
      List.current = current_list
      @email_blockers = (!@task.is_blocker?) ? @task.t_blockers.map {|blocker| blocker.mention_emails} : @task.mention_emails

      if (@task.destroy)
        if (!@task.is_blocker?)
          recipient = @task.user
          notification_type = notification_type("assigned_cancel")
          if (@task.assigner_id == currentUser.id) && (@task.assigner_id!= @task.user.id)
            Notification.create(recipient: recipient, actor:currentUser, notification_type: notification_type, notifiable: @task) if (notification_active?(recipient, notification_type,2))
          end
          @email_blockers.each do |emails|
            mentioned_in(emails,  @task, notification_type("cleared_blocker"), currentUser)
          end
        else
          mentioned_in(@email_blockers,  @task, notification_type("cleared_blocker"), currentUser)
        end
        flash[:notice] = "Task was deleted"
      else
        flash[:notice] = "We can't process your request now"
      end

    end
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    sender = current_user
    notification_type = notification_type("completed")
    recipient= ""

    if (@task.assigner_id != @task.user_id)
      recipient = !(current_user?(@task.assigner_id)) ? User.where(id: @task.assigner_id) : @task.user
    elsif !(current_user?(@task.user_id))
      recipient = @task.user
    end
    if !recipient.blank?
      Notification.create(recipient: recipient, actor:sender, notification_type: notification_type, notifiable: @task) if (notification_active?(recipient, notification_type,2))
    end
    if @task.has_blockers?
      @task.t_blockers.each do |t_blocker|
        tag_emails = t_blocker.mention_emails
        tag_emails.each do |email|
          recipient= User.find_by_email(email)
          notification_type = notification_type("cleared_blocker")
          Notification.create(recipient: recipient, actor:sender, notification_type: notification_type,notifiable: @task) if (notification_active?(recipient, notification_type,2))
          #  TaskMailer.mentioned_in_blocker(email, sender,@task).deliver_now if (notification_active?(recipient, notification_type,2))
        end
      end
    end
    flash[:notice] = "Task completed"

  end

  def incomplete
    recipient= ""
    if @task.update_attribute(:completed_at, nil)
      sender = current_user
      notification_type = notification_type("completed")
      if (@task.assigner_id != @task.user_id)
        recipient = !(current_user?(@task.assigner_id)) ? User.find_by(id: @task.assigner_id) : @task.user
      elsif !(current_user?(@task.user_id))
        recipient = @task.user
      end

      if !recipient.blank?
        Notification.create(recipient: recipient, actor:sender, notification_type: notification_type, notifiable: @task) if (notification_active?(recipient, notification_type,2))
      end
      flash[:notice] = "Task marked as incompleted"
    end
  end

  def changelist

    @task.list_after = list = List.find(params[:list_id])
    List.current = @task.list
     respond_to do |format|
      if can_change_list?(@task)
        if @task.update_attribute(:list_id, params[:list_id])
          flash[:notice] = "Task changed to the new list successfully"
          @htmlflash = TasksController.render(partial: "shared/flash_messages", locals: {"object": @task}).squish
          format.json { render :json => {:flash => flash[:notice]} }
        end
      else
        flash[:danger] = "You cannot change this task to this list"
        # @task.errors.add(:new_email,message: "You cannot change this task to this list")

app/helpers/tasks_helper.rb
module TasksHelper

  # def add_deadline
  #   @task.update_attribute(:deadline, params[:datepicker])
  #   respond_to do |format|
  #     format.html {  redirect_to @list, notice: "Task completed" }
  #     format.js
  #   end
  # end

  def mentioned_in(tag_emails, notifiable, notification_type, sender)
    tag_emails.each do |email|
      email.sub!(%r{^\+},"")
      if recipient = User.find_by_email(email)
        TaskMailer.mentioned_in_blocker(email, sender, notifiable).deliver_later if (notification_active?(recipient, notification_type,1))
        Notification.create(recipient:recipient, actor:sender, notification_type: notification_type, notifiable: notifiable) if (notification_active?(recipient, notification_type,2))
      end
     end
   end

   def can_change_list?(task)
     list_before = task.list
     list_after = task.list_after
     if (current_user.id != task.user_id)
        current_user.owner?(list_after) && current_user.owner?(list_before) && task.user.collaboration_lists.include?(list_after)
     else
       (current_user.owner?(list_after) || current_user.collaboration_lists.include?(list_after)) && (current_user.owner?(list_before) || current_user.collaboration_lists.include?(list_before))
     end
   end

   def can_change_user?(task)
     user_before = task.user
     user_after = task.user_after
     current_user.owner?(task.list) && (task.list.collaboration_users.include?(user_after) || (current_user.id == user_after.id))
   end
end

app/views/tasks/_edit_form.html.erb
<%= form_for(@task, :remote => true,:html => {:"data-behavior" => 'modal-form'}) do |f| %>
	<div class="input-field col">
		<% if @task.is_blocker? %>
			  <%#= hidden_field_tag 'tags_emails'  %>
				<%= f.text_field :detail, id: "mentionsBlocker_#{@task.id}", class: "inputor mentions", data: {:list_id=>"#{@task.parent_task.list_id}", :user_id => "#{@task.parent_task.user_id}"}, autocomplete: "off"  %>
				<label for="mentionsBlocker_<%= @task.id%>" class="active">Edit Blocker</label>
		<% else %>
			<%= f.text_field :detail, id: "detail_#{@task.id}", class: "inputor mentions", 'data-list_id'=> @task.list_id, 'data-user_id'=>  @task.user_id %>
			<label for="detail_<%= @task.id%>" class="active">Edit Task</label>
		<% end %>
  </div>
	<div class="row">
			<div class="col s6 input-field center-align">
				 	<%= link_to 'Back', lists_path, remote: true,:class => "waves-effect waves-light btn-medium submit lowercase su-btn btn-flat col s12 white" %>
			</div>
			<div class="col s6 input-field center-align">
					<a class="waves-effect waves-light btn-medium submit lowercase su-btn btn-flat col s12 white"><%= f.submit "Update"%></a>
			</div>
	</div>
<% end %>

app/views/tasks/_formBlocker.html.erb
<div class="row">
<%= form_for(@task.t_blockers.build, url:task_t_blockers_path(@task), method: :post, :remote => true,:html => {:"data-behavior" => 'modal-form', :id => 'create-blocker'}) do |f| %>
	<%= hidden_field_tag 'tags_emails'  %>
	    <div class="col s12">
					<div class="input-field">
							<%= f.text_field :detail, id: "mentionsBlocker", class: "inputor mentions",data: {:list_id=> "#{@task.list_id}", :user_id=> "#{@task.user_id}"},autocomplete: "off"  %>
					    <label for="mentionsBlocker">New Blocker</label>
				  </div>
					<div class="col s6 input-field center-align">
							<%= link_to 'Back', lists_path, remote: true,:class => "waves-effect waves-light btn-medium submit lowercase su-btn btn-flat col s12 white" %>
					</div>
					<div class="col s6 input-field center-align">
							<a class="waves-effect waves-light btn-medium submit lowercase su-btn btn-flat col s12 white"><%= f.submit "Create", id: "create-blocker"%></a>
					</div>
		</div>

<% end %>
</div>

app/views/tasks/_t_blocker.html.erb
<div id='blocker_<%= t_blocker.id %>' data-blocker-id="<%= t_blocker.id %>" class="blocker">
	 <%= link_to edit_task_t_blocker_path(id: t_blocker.id, task_id: t_blocker.parent_task_id),class: "blocker_detail", remote: true do %>
		 <%= label_tag "blocker_#{t_blocker.id}", t_blocker.detail, class: "truncate" %>
	 <% end %>
		<ul class="action-menu">
				<li>
		 			<%= link_to edit_task_t_blocker_path(id: t_blocker.id, task_id: t_blocker.parent_task_id), remote: true, data: {behavior: 'modal'} do %>
		 				 <i class="material-icons md-1rem md-dark md-inactive">mode_edit</i>
		 			<% end %>
	 		  </li>
				<li>
				 <%= link_to t_blocker, method: :delete, data: {confirm: "Are you sure?"}, remote: true  do %>
						<i class="material-icons md-1rem md-dark md-inactive">cancel</i>
				 <% end %>
			 </li>
		 </ul>
</div>

app/views/tasks/_task.html.erb
<%# task_created = (!task.completed?) ? task.task_created : ''%>
<% task_created =  task.task_created %>
<% draggable =  (currentUser.owner?(current_list)|| (currentUser.id== task.user_id))? "draggable" : "" %>
<%= content_tag :div, id: dom_id(task), class:"row #{task_created} #{draggable} task-box", data: {"task-id"=> task.id} do%>
	<div class="col s6 task-detail">
    <%= content_tag "p", id: "#{task.id}",class: (!task.completed?) ? "" : "truncate" do %>
			 <%= "#{task.detail.force_encoding("UTF-8")}" %>
		<% end %>
		<% if (!task.is_blocker?) %> <!--  && (!task.completed?)-->
				<ul class="menu-information">
						<% if (all_task?(current_list.id) ) %>
								<li><p id="list_name"><%= "#{task.list_belonging}"%></p></li>
						<% end %>
						<li><p> created at: "<%= "#{task.created_at.strftime('%a, %e %B')} " %>."</p></li>
						<li class="ms-deadline <%= (!task.deadline.nil?) ? 'active' : '' %>"><i class="material-icons md-18 md-red">&#xE858;</i><p id="alternate"><%= (!task.deadline.nil?) ? task.deadline.strftime('%a, %e %B') : '' %></p></li>
				</ul>
		<% end%>
	</div>
	<div class="col" id="menu">
			<ul class="menu-option">
					<li>
						<% if !task.completed? %>
							 <%= link_to importanttask_task_path(id: task.id, currentList: current_list.id ), :method=> :patch, remote: true do %>
									 <i class="tooltipped material-icons md-9rem <%= (task.important?)? 'md-jellow' : 'md-grey'  %>" id="md-important" data-position="top" data-delay="50" data-tooltip="Mark as important">&#xE838;</i>
							 <% end %>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <div class="input-group">
								<input type="text" class="tooltipped deadline-datepicker hidden-datepicker" id="deadline_<%= task.id%>" data-position="top" data-delay="50" data-tooltip="Add deadline">
								<%= content_tag :i, class: "i-btn-datepicker material-icons md-9rem #{(task.deadline?)? 'md-red' : 'md-grey'}", id: "btn-datepicker_#{task.id}", data: {"href" => "#{ add_deadline_task_path(id: task.id)}", "href-delete-deadline"=> "#{ delete_deadline_task_path(id: task.id)}" } do%>
									&#xE858;
								<% end%>
							</div>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <%= link_to edit_list_task_path(list_id: task.list_id, id: task.id, currentList: current_list.id ), remote: true, data: { behavior: 'modal' } do %>
									 <i class="tooltipped material-icons md-9rem md-grey" data-position="top" data-delay="50" data-tooltip="Edit Task">mode_edit</i>
							 <% end %>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <%= content_tag :a, class: "dropdown-button", href: "#", data: {"activates" => "dropdownlist_#{task.id}", "hover" => "false"},id: "dropdown_list_#{task.id}" do%>
								 <i class="tooltipped material-icons md-9rem md-grey" data-position="top" data-delay="50" data-tooltip="Change task to another list">view_list</i>
							 <% end %>
							 <ul id="dropdownlist_<%= task.id%>" class="dropdown-list">
			 		     	<% possible_all_lists = all_possible_lists(task.user_id, currentUser.id) %>
			 					<% possible_all_lists.each do |list| %>
			 					    <% if (list.id != task.list_id) %>
			 							    <li>
													<%= link_to changelist_task_path(list_id: list.id, id: task.id, currentList: current_list), remote: true, :method=> :patch  do%>
													   <%= list.name%>
														 <i class="material-icons md-1rem md-check">check</i>
													<% end %>
												</li>
			 							<% end %>
			 					<% end %>
			 			  </ul>
						<% end %>
					</li>
					<li>
						<%# if !task.completed? %>
						<%= form_for task, url:(!task.completed?) ? complete_task_path(:id => task.id, :currentList => task.list_id) : incomplete_task_path(:id => task.id,:currentList => task.list_id), remote: true do |f| %>
							<%= check_box_tag "completed[#{task.id}]", "#{task.id}", true, :name => "task_id"  %>
							<%= label_tag "completed_#{task.id}", "", class: "tooltipped", "data-position" => "top", "data-delay" => "50", "data-tooltip" => "Mark task as #{(!task.completed?) ? "completed" : "incomplete"}"%>
							<%#= f.submit "Update" %>
						<% end %>
						<%# end %>
					</li>
					<li>
							<%= link_to task, method: :delete, data: {confirm: "Are you sure you want to delete it?"}, remote: true do %>
								 <i class="tooltipped material-icons md-9rem md-grey" data-position="top" data-delay="50" data-tooltip="Delete task">cancel</i>
							<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <i class="material-icons md-18 md-red" data-hasblockers="<%= task.t_blockers.count!=0 %>" >warning</i>
							 <%= link_to new_task_t_blocker_path(list_id: task.list_id, task_id: task.id,user_id: task.user_id),id: "link-blocker_#{task.id}", remote: true, data: { behavior: 'modal' }  do %>
									<%= content_tag :i, class: "tooltipped material-icons md-9rem md-#{(task.t_blockers.count!=0) ? 'red' : 'grey'}", data: {"position"=> "top", "delay"=>"50","tooltip"=>"Add blocker", "hasblockers"=>"#{task.t_blockers.count!=0}"} do%>
											warning
									<% end %>
							 <% end %>
						<% end %>
				</li>
		</ul>
	</div>
	<div class="col s3 show_blockers text-align:left" id="show_blockers_<%= task.id%>">
		<% if !task.completed? %>
			<%= render(partial: "tasks/t_blocker", collection: task.t_blockers) %>
		<% end %>
	</div>
<% end%>

app/views/tasks/_taskCreate.html.erb
<!-- <p id="<%= task.id%>"><%= "#{task.detail} #{task.completed_at}" %></p>
<% if (!task.is_blocker?) && (!task.completed?) %>
	<ul class="menu-option menu-information">
	<% if (all_task?(task.list_id) ) %>
		<li><p><%= "#{task.list_belonging}"%></p></li>
		<li>/</li>
	<% end %>
		<li><p><%= "#{distance_of_time_in_words(task.created_at, Time.now, include_seconds: true)} ago" %></p></li>
		<li>/</li>
		<li><p> created_at: <%= "#{task.created_at.strftime('%m:%d:%Y')} " %></p></li>
		<% if (task.deadline?) %>
			<li>/</li>
		  <li><i class="material-icons md-18 md-red">&#xE858;</i><p><%= "#{task.deadline}" %></p></li>
		<% end %>
	</ul>
<% end%> -->
<!-- <% cache task do %> -->
<div id='task_<%= task.id%>' class="row	<%= (!task.completed?)? task.task_created : ''  %>" data-task-id = "<%= task.id%>">
	<div class="col s6">
		<p id="<%= task.id%>"  style="<%= (task.completed?)? 'text-decoration: line-through;' : ''  %>"><%= "#{task.detail} #{task.completed_at}" %></p>
		<% if (!task.is_blocker?) && (!task.completed?) %>
				<ul class="menu-information">
				<% if (all_task?(task.list_id) ) %>
						<li><p><%= "#{task.list_belonging}"%></p></li>
						<li>/</li>
				<% end %>
						<li><p><%= "#{distance_of_time_in_words(task.created_at, Time.now, include_seconds: true)} ago" %></p></li>
						<li>/</li>
						<li><p> created_at: "<%= "#{task.created_at.strftime('%a, %e %B')} " %>."</p></li>
						<% if (task.deadline?) %>
							<li>/</li>
						  <li><i class="material-icons md-18 md-red">&#xE858;</i><p><%= "#{task.deadline}" %></p></li>
						<% end %>
				</ul>
		<% end%>
	</div>
	<div class="col" id="menu">
		<% if (current_date == Date.today) %>
				<ul class="menu-option">
					<li>
						<% if !task.completed? %>
							 <%= link_to edit_list_task_path(list_id: task.list_id, id: task.id), remote: true do %>
									 <i class="material-icons md-18 md-<%= (task.important?)? today(task.created_at.to_date) : 'dark md-inactive'  %>">&#xE838;</i>
							 <% end %>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <%= link_to edit_list_task_path(list_id: task.list_id, id: task.id), remote: true do %>
									 <i class="material-icons md-18 md-<%= (task.deadline?)? 'red' : 'dark md-inactive'%>">&#xE858;</i>
							 <% end %>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <%= link_to edit_list_task_path(list_id: task.list_id, id: task.id), remote: true, data: { behavior: 'modal' } do %>
									 <i class="material-icons md-18 md-dark md-inactive">mode_edit</i>
							 <% end %>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <a class='dropdown-button' href='#' data-activates='dropdownlist_<%= task.id%>'>
								 <i class="material-icons md-18  md-dark md-inactive">view_list</i>
							 </a>
							 <ul id="dropdownlist_<%= task.id%>" class="dropdown-list">
			 					<% @lists = User.find(task.user_id).created_lists.all.order('created_at')%>
			 		     	<% @collaboration_lists = User.find(task.user_id).collaboration_lists.all%>
			 		     	<% @current_all_lists ||= @lists + @collaboration_lists %>
			 					<% @current_all_lists.each do |list| %>
			 					    <% if (list.id != task.list_id) %>
			 							    <li><%= link_to list.name, changelist_task_path(list_id: list.id, id: task.id ), remote: true, :method=> :patch  %></li>
			 							<% end %>
			 					<% end %>
			 			  </ul>
						<% end %>
					</li>
					<li>
						<% if !task.completed? %>
								<%= form_for task, url: complete_task_path(:id => task.id, :list_id => task.list_id), remote: true do |f| %>
								<%= check_box_tag "completed[#{task.id}]", "#{task.id}", true, :name => "task_id", disabled: task.completed?  %>
								<%= label_tag "completed_#{task.id}", ""%>
								<%= f.submit "Update" %>
								<% end %>
						<% end %>
					</li>
					<li>
							<%= link_to task, method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
								 <i class="material-icons md-18 md-dark md-inactive">cancel</i>
							<% end %>
					</li>
					<li>
						<% if !task.completed? %>
							 <!-- task_t_blockers_path -->
							 <%= link_to new_task_t_blocker_path(list_id: task.list_id, task_id: task.id,user_id: task.user_id),id: 'completed', remote: true, data: { behavior: 'modal' }  do %>
									<i class="material-icons md-18 md-<%= (!task.t_blockers.blank?) ? 'red':'dark md-inactive' %>">warning</i>
							 <% end %>
						<% end %>
					</li>
				</ul>

		<% end %>
	</div>
	<div class="col s3 show_blockers text-align:left" id="show_blockers_<%= task.id%>">
		<% if !task.completed? %>
			<%= render(partial: "tasks/t_blocker", collection: task.t_blockers) %>
		<% end %>
	</div>
</div>
		<!-- <% end %> -->

app/views/tasks/changelist.js.erb
<% if @task.errors.any? %>
  $("#error_message").html("<%= j render :partial => 'shared/flash_messages', :locals => {:object => @task } %>");
<% end%>

app/views/tasks/destroy.js.erb
$('.modal').modal("close");
$('#ms-modal-dialog').modal("close");

app/views/tasks/edit.html.erb
<div class="forms">
		<h2 class="modal-title center-align">Edit Task</h2>
		<%= render partial: 'edit_form'  %>
</div>